= SpreadShare
:toc: left
:sectnums:
:toclevels: 1
:table-caption:
:linkattrs:

----
Kontakt: a.saydam@students.htl-leonding.ac.at
----


== Projektinformationen
[cols="h, s"]
|===
| Projektantrag von | Saydam
|===

[cols="h, s"]
|===
| Projektbezeichnung | SpreadShare
| Projektauftraggeber | H.Aitenbichler & M.Haslinger
| Projekthintergrund | Passanten erhalten Flyer, Broschüren und andere 
                        Printmedien in ausgedruckter Form, nehmen diese ohne echtes Interesse an und entsorgen sie anschließend.
| Projektergebnis | Keine herumfliegenden Printmedien und weniger 
                        Umweltverschmutzung.
| Projektziel(e) | Den Werbenden sowie potenziellen Interessenten ein 
                        angenehmeres und umweltbewussteres Umfeld zu schaffen.
| Projektbeschreibung | Die Anwendung ermöglicht es Interessenten, mittels
                         eines Bluetooth Beacons Daten zu empfangen. Dadurch ersparen sie sich den Papierflyer, Broschüren, Speisekarten und können stattdessen eine Vorschau auf ihrem Handy sehen und diesen bei Bedarf herunterladen.
|===

== Projektphasen / Meilensteine

Beschreibung der Projektphasen und deren überprüfbarer Zwischenergebnisse.

Hier finden Sie unsere https://github.com/SaydamArda/SpreadShare/milestones[Meilensteine]

== Projektdaten

[cols="h, s"]
|===
| Projektstart | 12.09.2024
| Projektende | --.--.2025
|===

== Projekt

[cols="h, s"]
|===
| Projektrisiken | Fehlendes Interesse aufgrund der potenziellen Gefahr 
                    durch Viren oder Ähnliches.
| Projektorganisation | Projektleiter: Arda Saydam

                        Projektteam: Fabian Stroschneider, Ademir Kurtic,
                        Antonio Ignac
| Abschluss des Projektauftrags | Datum, Unterschriften aller Verantwortlichen
|===